/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SearchRouteImport } from './routes/search'
import { Route as MovieIndexRouteImport } from './routes/movie/index'
import { Route as MovieMovieIdRouteImport } from './routes/movie/$movieId'
import { Route as PersonPersonIdRouteImport } from './routes/person/$personId'
import { Route as TvIndexRouteImport } from './routes/tv/index'
import { Route as TvSeriesIdRouteImport } from './routes/tv/$seriesId'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as TvSeriesIdSeasonSeasonNumberRouteImport } from './routes/tv/$seriesId/season/$seasonNumber'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const MovieIndexRoute = MovieIndexRouteImport.update({
  id: '/movie/',
  path: '/movie/',
  getParentRoute: () => rootRouteImport,
} as any)
const MovieMovieIdRoute = MovieMovieIdRouteImport.update({
  id: '/movie/$movieId',
  path: '/movie/$movieId',
  getParentRoute: () => rootRouteImport,
} as any)
const PersonPersonIdRoute = PersonPersonIdRouteImport.update({
  id: '/person/$personId',
  path: '/person/$personId',
  getParentRoute: () => rootRouteImport,
} as any)
const TvIndexRoute = TvIndexRouteImport.update({
  id: '/tv/',
  path: '/tv/',
  getParentRoute: () => rootRouteImport,
} as any)
const TvSeriesIdRoute = TvSeriesIdRouteImport.update({
  id: '/tv/$seriesId',
  path: '/tv/$seriesId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const TvSeriesIdSeasonSeasonNumberRoute =
  TvSeriesIdSeasonSeasonNumberRouteImport.update({
    id: '/season/$seasonNumber',
    path: '/season/$seasonNumber',
    getParentRoute: () => TvSeriesIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/search': typeof SearchRoute
  '/movie/$movieId': typeof MovieMovieIdRoute
  '/person/$personId': typeof PersonPersonIdRoute
  '/tv/$seriesId': typeof TvSeriesIdRouteWithChildren
  '/movie/': typeof MovieIndexRoute
  '/tv/': typeof TvIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/tv/$seriesId/season/$seasonNumber': typeof TvSeriesIdSeasonSeasonNumberRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/search': typeof SearchRoute
  '/movie/$movieId': typeof MovieMovieIdRoute
  '/person/$personId': typeof PersonPersonIdRoute
  '/tv/$seriesId': typeof TvSeriesIdRouteWithChildren
  '/movie': typeof MovieIndexRoute
  '/tv': typeof TvIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/tv/$seriesId/season/$seasonNumber': typeof TvSeriesIdSeasonSeasonNumberRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/search': typeof SearchRoute
  '/movie/$movieId': typeof MovieMovieIdRoute
  '/person/$personId': typeof PersonPersonIdRoute
  '/tv/$seriesId': typeof TvSeriesIdRouteWithChildren
  '/movie/': typeof MovieIndexRoute
  '/tv/': typeof TvIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/tv/$seriesId/season/$seasonNumber': typeof TvSeriesIdSeasonSeasonNumberRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/search'
    | '/movie/$movieId'
    | '/person/$personId'
    | '/tv/$seriesId'
    | '/movie/'
    | '/tv/'
    | '/api/auth/$'
    | '/tv/$seriesId/season/$seasonNumber'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/search'
    | '/movie/$movieId'
    | '/person/$personId'
    | '/tv/$seriesId'
    | '/movie'
    | '/tv'
    | '/api/auth/$'
    | '/tv/$seriesId/season/$seasonNumber'
  id:
    | '__root__'
    | '/'
    | '/search'
    | '/movie/$movieId'
    | '/person/$personId'
    | '/tv/$seriesId'
    | '/movie/'
    | '/tv/'
    | '/api/auth/$'
    | '/tv/$seriesId/season/$seasonNumber'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SearchRoute: typeof SearchRoute
  MovieMovieIdRoute: typeof MovieMovieIdRoute
  PersonPersonIdRoute: typeof PersonPersonIdRoute
  TvSeriesIdRoute: typeof TvSeriesIdRouteWithChildren
  MovieIndexRoute: typeof MovieIndexRoute
  TvIndexRoute: typeof TvIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/movie/': {
      id: '/movie/'
      path: '/movie'
      fullPath: '/movie/'
      preLoaderRoute: typeof MovieIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/movie/$movieId': {
      id: '/movie/$movieId'
      path: '/movie/$movieId'
      fullPath: '/movie/$movieId'
      preLoaderRoute: typeof MovieMovieIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/person/$personId': {
      id: '/person/$personId'
      path: '/person/$personId'
      fullPath: '/person/$personId'
      preLoaderRoute: typeof PersonPersonIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tv/': {
      id: '/tv/'
      path: '/tv'
      fullPath: '/tv/'
      preLoaderRoute: typeof TvIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tv/$seriesId': {
      id: '/tv/$seriesId'
      path: '/tv/$seriesId'
      fullPath: '/tv/$seriesId'
      preLoaderRoute: typeof TvSeriesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tv/$seriesId/season/$seasonNumber': {
      id: '/tv/$seriesId/season/$seasonNumber'
      path: '/season/$seasonNumber'
      fullPath: '/tv/$seriesId/season/$seasonNumber'
      preLoaderRoute: typeof TvSeriesIdSeasonSeasonNumberRouteImport
      parentRoute: typeof TvSeriesIdRoute
    }
  }
}

interface TvSeriesIdRouteChildren {
  TvSeriesIdSeasonSeasonNumberRoute: typeof TvSeriesIdSeasonSeasonNumberRoute
}

const TvSeriesIdRouteChildren: TvSeriesIdRouteChildren = {
  TvSeriesIdSeasonSeasonNumberRoute: TvSeriesIdSeasonSeasonNumberRoute,
}

const TvSeriesIdRouteWithChildren = TvSeriesIdRoute._addFileChildren(
  TvSeriesIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SearchRoute: SearchRoute,
  MovieMovieIdRoute: MovieMovieIdRoute,
  PersonPersonIdRoute: PersonPersonIdRoute,
  TvSeriesIdRoute: TvSeriesIdRouteWithChildren,
  MovieIndexRoute: MovieIndexRoute,
  TvIndexRoute: TvIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
